// app/formulaire-fiscal/copy.ts

export const COPY = {
  fr: {
    brand: "ComptaNet Québec",
    formName: "Formulaire fiscal",
    disconnect: "Se déconnecter",
    intro:
      "Merci de remplir ce formulaire après avoir créé votre compte. Nous utilisons ces informations pour préparer vos déclarations d’impôt au Canada (fédéral) et, si applicable, au Québec.",
    fixBeforeContinue: "À corriger avant de continuer",
    missingRequired:
      "❌ Certaines informations obligatoires manquent. Corrigez la liste ci-dessous.",
    preparing: "⏳ Préparation du dossier…",
    redirecting: "✅ Redirection vers le dépôt…",
    continue: "Continuer →",
    docsNext: "Étape suivante : dépôt des documents.",
    completeToContinue: "Complétez les champs obligatoires pour continuer.",
    docsLoading: "Chargement des documents…",
    docsAlready: (n: number) => `${n} document(s) déjà au dossier.`,
    docsTitle: "Documents au dossier",
    openDoc: (name: string) => `Ouvrir — ${name}`,

    sections: {
      clientTitle: "Informations du client",
      clientDesc: "Informations essentielles pour l’ouverture du dossier.",
      spouseTitle: "Conjoint",
      spouseDesc: "À remplir seulement si applicable.",
      medsTitle: "Assurance médicaments (Québec)",
      medsDesc: "RAMQ / régimes privés : indiquez qui vous couvrait et les périodes.",
      dependantsTitle: "Personnes à charge",
      dependantsDesc: "Ajoutez vos enfants / personnes à charge.",
      questionsTitle: "Informations fiscales additionnelles",
      questionsDesc: "Questions générales pour compléter correctement le dossier.",
      confirmsTitle: "Confirmations obligatoires",
      confirmsDesc: "Sans ces confirmations, le dossier ne peut pas continuer.",
    },

    fields: {
      firstName: "Prénom",
      lastName: "Nom",
      sin: "Numéro d’assurance sociale (NAS)",
      sinPh: "123-456-789",
      dob: "Date de naissance (JJ/MM/AAAA)",
      dobPh: "01/01/1990",
      marital: "État civil",
      maritalChanged: "Mon état civil a changé durant l'année",
      prevMarital: "Ancien état civil",
      prevMaritalPh: "ex.: Célibataire",
      changeDate: "Date du changement (JJ/MM/AAAA)",
      changeDatePh: "15/07/2024",
      phone: "Téléphone",
      mobile: "Cellulaire",
      email: "Courriel",
      address: "Adresse (rue)",
      apt: "App.",
      aptPh: "#201",
      city: "Ville",
      province: "Province",
      postal: "Code postal",
      postalPh: "G1V 0A6",
    },

    spouse: {
      hasSpouse: "J'ai un conjoint / conjointe",
      includeSpouse: "Traiter aussi la déclaration du conjoint",
      spouseNetIncome: "Revenu net approximatif du conjoint ($)",
      spouseNetIncomePh: "ex.: 42 000",
      spouseFirstName: "Prénom (conjoint)",
      spouseLastName: "Nom (conjoint)",
      spouseSin: "NAS (conjoint)",
      spouseDob: "Date de naissance (JJ/MM/AAAA)",
      spousePhone: "Téléphone (conjoint)",
      spouseMobile: "Cellulaire (conjoint)",
      spouseEmail: "Courriel (conjoint)",
      sameAddress: "L'adresse du conjoint est identique à la mienne",
      spouseAddress: "Adresse (rue) - conjoint",
    },

    meds: {
      clientCoverage: "Couverture du client",
      spouseCoverage: "Couverture du conjoint",
      yourCoverage: "Votre couverture médicaments",
      spouseCoverageLabel: "Couverture médicaments du conjoint",
      addPeriod: "+ Ajouter une période",
      from: "De (JJ/MM/AAAA)",
      to: "À (JJ/MM/AAAA)",
      fromPh: "01/01/2024",
      toPh: "31/12/2024",
      opts: {
        ramq: "Régime public (RAMQ)",
        prive: "Mon régime collectif privé",
        conjoint: "Régime du conjoint / d'un parent",
      },
    },

    dependants: {
      none: "Aucune personne à charge ajoutée.",
      titleN: (n: number) => `Personne à charge #${n}`,
      remove: "Supprimer",
      add: "+ Ajouter une personne à charge",
      sinIfAny: "NAS (si attribué)",
      sex: "Sexe",
      sexM: "M",
      sexF: "F",
      sexX: "Autre / préfère ne pas dire",
    },

    questions: {
      taxYear: "Année d’imposition (ex.: 2025)",
      taxYearPh: "ex.: 2025",
      livedAlone: "Avez-vous habité seul(e) toute l'année (sans personne à charge) ?",
      peopleCount: "Au 31/12, combien de personnes vivaient avec vous ?",
      peopleCountPh: "ex.: 1",
      foreignAssets: "Avez-vous plus de 100 000 $ de biens à l'étranger ?",
      citizen: "Êtes-vous citoyen(ne) canadien(ne) ?",
      nonResident: "Êtes-vous non-résident(e) du Canada aux fins fiscales ?",
      homeTx: "Avez-vous acheté une première habitation ou vendu votre résidence principale cette année ?",
      techCall: "Souhaitez-vous qu'un technicien vous appelle ?",
      copy: "Comment voulez-vous recevoir votre copie d'impôt ?",
      copyPortal: "Espace client",
      copyEmail: "Courriel",
    },

    confirms: {
      exact: "Je confirme que toutes les informations fournies sont exactes.",
      complete: "Je confirme avoir fourni toutes les informations requises pour le traitement.",
      fees: "Je comprends que les frais peuvent varier selon la complexité du dossier.",
      delays: "Je comprends qu’un dossier incomplet peut retarder le traitement.",
    },
  },

  en: {
    brand: "ComptaNet Québec",
    formName: "Tax form",
    disconnect: "Sign out",
    intro:
      "Please complete this form after creating your account. We use this information to prepare your Canadian (federal) tax return and, if applicable, your Québec return.",
    fixBeforeContinue: "Fix before continuing",
    missingRequired:
      "❌ Some required information is missing. Please fix the list below.",
    preparing: "⏳ Preparing your file…",
    redirecting: "✅ Redirecting to upload…",
    continue: "Continue →",
    docsNext: "Next step: document upload.",
    completeToContinue: "Complete required fields to continue.",
    docsLoading: "Loading documents…",
    docsAlready: (n: number) => `${n} document(s) already on file.`,
    docsTitle: "Documents on file",
    openDoc: (name: string) => `Open — ${name}`,

    sections: {
      clientTitle: "Client information",
      clientDesc: "Essential information to open your file.",
      spouseTitle: "Spouse",
      spouseDesc: "Fill out only if applicable.",
      medsTitle: "Prescription drug insurance (Québec)",
      medsDesc: "RAMQ / private plans: indicate coverage and periods.",
      dependantsTitle: "Dependants",
      dependantsDesc: "Add your children / dependants.",
      questionsTitle: "Additional tax info",
      questionsDesc: "General questions to complete your file correctly.",
      confirmsTitle: "Required confirmations",
      confirmsDesc: "Without these confirmations, you cannot continue.",
    },

    fields: {
      firstName: "First name",
      lastName: "Last name",
      sin: "Social Insurance Number (SIN)",
      sinPh: "123-456-789",
      dob: "Date of birth (DD/MM/YYYY)",
      dobPh: "01/01/1990",
      marital: "Marital status",
      maritalChanged: "My marital status changed during the year",
      prevMarital: "Previous marital status",
      prevMaritalPh: "e.g., Single",
      changeDate: "Change date (DD/MM/YYYY)",
      changeDatePh: "15/07/2024",
      phone: "Phone",
      mobile: "Mobile",
      email: "Email",
      address: "Address (street)",
      apt: "Apt.",
      aptPh: "#201",
      city: "City",
      province: "Province",
      postal: "Postal code",
      postalPh: "G1V 0A6",
    },

    spouse: {
      hasSpouse: "I have a spouse / partner",
      includeSpouse: "Include spouse tax return as well",
      spouseNetIncome: "Spouse approximate net income ($)",
      spouseNetIncomePh: "e.g., 42,000",
      spouseFirstName: "Spouse first name",
      spouseLastName: "Spouse last name",
      spouseSin: "Spouse SIN",
      spouseDob: "Spouse date of birth (DD/MM/YYYY)",
      spousePhone: "Spouse phone",
      spouseMobile: "Spouse mobile",
      spouseEmail: "Spouse email",
      sameAddress: "Spouse address is the same as mine",
      spouseAddress: "Spouse address (street)",
    },

    meds: {
      clientCoverage: "Client coverage",
      spouseCoverage: "Spouse coverage",
      yourCoverage: "Your prescription drug coverage",
      spouseCoverageLabel: "Spouse prescription drug coverage",
      addPeriod: "+ Add a period",
      from: "From (DD/MM/YYYY)",
      to: "To (DD/MM/YYYY)",
      fromPh: "01/01/2024",
      toPh: "31/12/2024",
      opts: {
        ramq: "Public plan (RAMQ)",
        prive: "My private group plan",
        conjoint: "Spouse/parent plan",
      },
    },

    dependants: {
      none: "No dependant added.",
      titleN: (n: number) => `Dependant #${n}`,
      remove: "Remove",
      add: "+ Add a dependant",
      sinIfAny: "SIN (if assigned)",
      sex: "Sex",
      sexM: "M",
      sexF: "F",
      sexX: "Other / prefer not to say",
    },

    questions: {
      taxYear: "Tax year (e.g., 2025)",
      taxYearPh: "e.g., 2025",
      livedAlone: "Did you live alone all year (no dependants)?",
      peopleCount: "On 12/31, how many people lived with you?",
      peopleCountPh: "e.g., 1",
      foreignAssets: "Do you have more than $100,000 in foreign assets?",
      citizen: "Are you a Canadian citizen?",
      nonResident: "Are you a non-resident of Canada for tax purposes?",
      homeTx: "Did you buy a first home or sell your principal residence this year?",
      techCall: "Do you want a technician to call you?",
      copy: "How would you like to receive your tax copy?",
      copyPortal: "Client portal",
      copyEmail: "Email",
    },

    confirms: {
      exact: "I confirm that all information provided is accurate.",
      complete: "I confirm that I provided all required information.",
      fees: "I understand fees may vary depending on file complexity.",
      delays: "I understand an incomplete file can delay processing.",
    },
  },

  es: {
    brand: "ComptaNet Québec",
    formName: "Formulario fiscal",
    disconnect: "Cerrar sesión",
    intro:
      "Complete este formulario después de crear su cuenta. Usamos esta información para preparar su declaración de impuestos de Canadá (federal) y, si corresponde, la de Québec.",
    fixBeforeContinue: "Corrija antes de continuar",
    missingRequired:
      "❌ Faltan datos obligatorios. Corrija la lista a continuación.",
    preparing: "⏳ Preparando su expediente…",
    redirecting: "✅ Redirigiendo a la carga…",
    continue: "Continuar →",
    docsNext: "Siguiente paso: carga de documentos.",
    completeToContinue: "Complete los campos obligatorios para continuar.",
    docsLoading: "Cargando documentos…",
    docsAlready: (n: number) => `${n} documento(s) ya en el expediente.`,
    docsTitle: "Documentos en el expediente",
    openDoc: (name: string) => `Abrir — ${name}`,

    sections: {
      clientTitle: "Información del cliente",
      clientDesc: "Información esencial para abrir el expediente.",
      spouseTitle: "Cónyuge",
      spouseDesc: "Complete solo si corresponde.",
      medsTitle: "Seguro de medicamentos (Québec)",
      medsDesc: "RAMQ / planes privados: indique la cobertura y los períodos.",
      dependantsTitle: "Dependientes",
      dependantsDesc: "Agregue sus hijos / dependientes.",
      questionsTitle: "Información fiscal adicional",
      questionsDesc: "Preguntas generales para completar correctamente el expediente.",
      confirmsTitle: "Confirmaciones obligatorias",
      confirmsDesc: "Sin estas confirmaciones, no puede continuar.",
    },

    fields: {
      firstName: "Nombre",
      lastName: "Apellido",
      sin: "Número de seguro social (SIN/NAS)",
      sinPh: "123-456-789",
      dob: "Fecha de nacimiento (DD/MM/AAAA)",
      dobPh: "01/01/1990",
      marital: "Estado civil",
      maritalChanged: "Mi estado civil cambió durante el año",
      prevMarital: "Estado civil anterior",
      prevMaritalPh: "p. ej., Soltero(a)",
      changeDate: "Fecha del cambio (DD/MM/AAAA)",
      changeDatePh: "15/07/2024",
      phone: "Teléfono",
      mobile: "Móvil",
      email: "Correo electrónico",
      address: "Dirección (calle)",
      apt: "Apto.",
      aptPh: "#201",
      city: "Ciudad",
      province: "Provincia",
      postal: "Código postal",
      postalPh: "G1V 0A6",
    },

    spouse: {
      hasSpouse: "Tengo cónyuge / pareja",
      includeSpouse: "Incluir también la declaración del cónyuge",
      spouseNetIncome: "Ingreso neto aproximado del cónyuge ($)",
      spouseNetIncomePh: "p. ej., 42 000",
      spouseFirstName: "Nombre (cónyuge)",
      spouseLastName: "Apellido (cónyuge)",
      spouseSin: "NAS/SIN (cónyuge)",
      spouseDob: "Fecha de nacimiento (DD/MM/AAAA)",
      spousePhone: "Teléfono (cónyuge)",
      spouseMobile: "Móvil (cónyuge)",
      spouseEmail: "Correo (cónyuge)",
      sameAddress: "La dirección del cónyuge es la misma que la mía",
      spouseAddress: "Dirección (calle) - cónyuge",
    },

    meds: {
      clientCoverage: "Cobertura del cliente",
      spouseCoverage: "Cobertura del cónyuge",
      yourCoverage: "Su cobertura de medicamentos",
      spouseCoverageLabel: "Cobertura de medicamentos del cónyuge",
      addPeriod: "+ Agregar un período",
      from: "Desde (DD/MM/AAAA)",
      to: "Hasta (DD/MM/AAAA)",
      fromPh: "01/01/2024",
      toPh: "31/12/2024",
      opts: {
        ramq: "Plan público (RAMQ)",
        prive: "Plan colectivo privado",
        conjoint: "Plan del cónyuge/padre",
      },
    },

    dependants: {
      none: "No hay dependientes agregados.",
      titleN: (n: number) => `Dependiente #${n}`,
      remove: "Eliminar",
      add: "+ Agregar un dependiente",
      sinIfAny: "NAS/SIN (si existe)",
      sex: "Sexo",
      sexM: "M",
      sexF: "F",
      sexX: "Otro / prefiero no decir",
    },

    questions: {
      taxYear: "Año fiscal (p. ej., 2025)",
      taxYearPh: "p. ej., 2025",
      livedAlone: "¿Vivió solo(a) todo el año (sin dependientes)?",
      peopleCount: "Al 31/12, ¿cuántas personas vivían con usted?",
      peopleCountPh: "p. ej., 1",
      foreignAssets: "¿Tiene más de $100,000 en bienes en el extranjero?",
      citizen: "¿Es ciudadano(a) canadiense?",
      nonResident: "¿Es no residente de Canadá para fines fiscales?",
      homeTx: "¿Compró una primera vivienda o vendió su residencia principal este año?",
      techCall: "¿Desea que un técnico le llame?",
      copy: "¿Cómo desea recibir su copia de impuestos?",
      copyPortal: "Portal del cliente",
      copyEmail: "Correo electrónico",
    },

    confirms: {
      exact: "Confirmo que toda la información proporcionada es exacta.",
      complete: "Confirmo que proporcioné toda la información requerida.",
      fees: "Entiendo que pueden aplicarse cargos adicionales según la complejidad.",
      delays: "Entiendo que un expediente incompleto puede retrasar el procesamiento.",
    },
  },
} as const;

export type CopyLang = keyof typeof COPY;
export type CopyPack = (typeof COPY)[CopyLang];

export function pickCopy(lang: string | null | undefined): CopyLang {
  const x = (lang || "").toLowerCase();
  return x === "fr" || x === "en" || x === "es" ? (x as CopyLang) : "fr";
}
